### ISSUE TITLE
CLI options for IDE integrations.

### ISSUE THREAD

**Issue by 0xorial** [ljharb/tape#582]
I was looking at a way to integrate tape in an IDE ([vscode in particular](https://code.visualstudio.com/api/extension-guides/testing)) and it seems that it is missing 3 features: 
- CLI option to run only one test
- CLI option to exclude a certain test
- CLI option to [dry-run](https://github.com/mochajs/mocha/pull/4640), the tests - enumerate them to IDE without running.

Do you think it is feasible, would you be open to a PR for that and in that case do you think it is difficult to add?

**Comment by ljharb** [comment]
I don't think these are really possible.

For the third, the tests aren't static - they have to actually run to notify `tape` what the tests even *are*. It only makes sense in mocha's BDD style because you can't nest `it`s, but in tap/tape's style, you can nest tests as much as you want.

For the first or second, how would you identify a given test? Test descriptions aren't guaranteed to be unique, and using the number isn't deterministic (see #301).

**Comment by ljharb** [comment]
There might be some usefulness in a pattern-based approach to match on test descriptions - which would be also available as a CLI flag. Are you interested in sketching out how something like that might work?

**Comment by 0xorial** [comment]
Is anyone working on this in Windows? I spent ~1h trying to get the tests to succeed, wondering if I am missing something obvious... :/

**Comment by ljharb** [comment]
@0xorial afaik it works fine in windows, but certainly i don’t develop in it. If you’re having trouble, please file a separate issue.
